### PR TITLE
[Update] Dynamic Menu Options + Hold/Release

### PR DESCRIPTION
**Pull request by ItsANoBrainer**
This update also contains the required code for the Customs polyzone update found here:
https://github.com/qbcore-framework/qb-customs/pull/71

- Can now dynamically add/remove entries to the menu, use the SetupCustomsMenu() function as an example
- Radial menu is now a hold/release instead of a toggle. Holding f1 keeps the menu open while letting it go closes it

### CODE REVIEW

**Comment by BerkieBb** [comment]
Instead of adding a delay, add a + and - keymapping, and why change from F1 to Z, that'll trigger the inventory hotbar when you open the radialmenu

**Comment by BerkieBb** [comment]
Can't fit the changes that I want to suggest in a review so I'll make a PR on your repo

**Review by TonybynMp4 — APPROVED** [review]

**Comment by JonasDev99** [comment]
Why change from toggle to hold? I prefer toggle but I added an option in qb-hud for mine so one can choose between hold and toggle.

**Comment by ItsANoBrainer** [comment]
Hold/Release is smoother UI experience in my opinion, as well as I think many people prefer it. 

You can easily change it back if you want, or submit a PR to have it as a config option.

**Comment by JonasDev99** [comment]
Ok.  Also my suggestion is to move the qb-customs and any other code that is actually from a different script out of the radial menu because that would create less dependencies (kinda single responsibility style). I have exports in mine to manipulate the radial menu from anywhere (credits to someone on Discord...)

 ```
exports('AddOption', function(id, data)
    Config.MenuItems[id] = data
end)

exports('RemoveOption', function(id)
    Config.MenuItems[id] = nil
end)
```
That way the code that actually belongs to qb-customs stays in the qb-customs resource.

**Comment by ItsANoBrainer** [comment]
Good idea, I will review this when I get some time.

**Comment by JonasDev99** [comment]
I submitted a PR on your repos qb-radialmenu and qb-customs. Lmk what you think

**Comment by SodaPortal** [comment]
Hold/Release may pair nicely with the ability to navigate the menu with arrow keys to make this a full no-frills UI/UX experience and to add options

**Comment by ItsANoBrainer** [comment]
@SodaPortal Interesting idea! Although that is more changing up the radial menu source code rather than just the connector between the two. We're always open for PRs!

**Comment by ItsANoBrainer** [comment]
@JonasDev99 I will definitely take a look when I get a moment, thanks!

**Review by uShifty — CHANGES_REQUESTED** [review]
Revert the changes made to the function SetupJobMenu. I needed to readd `local index = #Config.MenuItems + 1` to replace the hard coded value of 4 to fix the qb-customs radial menu feature.

**Comment by JonasDev99** [comment]
Can confirm, qb-customs does not work with this update. https://medal.tv/games/gta-v/clips/fruDLRZAxXt-0/d1337QAQnaJ8?invite=cr-MSxkV1ksNzQ5Nzg5OSw

**Comment by JonasDev99** [comment]
@DannysRP Make sure you change the config of qb-customs. There is an option to use the radialmenu.

**Comment by ItsANoBrainer** [comment]
> Revert the changes made to the function SetupJobMenu. I needed to readd `local index = #Config.MenuItems + 1` to replace the hard coded value of 4 to fix the qb-customs radial menu feature.

Can’t do that or it won’t change the job menu on job change or clear at all.

**Comment by JonasDev99** [comment]
I downloaded both your qb-radialmenu and qb-customs as a zip and dropped them in my qb folder. Then I tested qb-customs with the "press E" option. I then changed it to radialmenu in the config and tried again and it didn't work. It worked with my implementation / PR if I remember correctly. I will test it again when I get home in 30min.

**Comment by TonybynMp4** [comment]
working fine for me 🤔

**Comment by DannysRP** [comment]
I have the exact copy of what you did without changes. I tried without the radial menu option where you press E, this works except it will show all options at locations that have only one option available. Benny's for example has only repair in their options but I could do all cosmetics and no internal mods. When I set the radial menu option to true it doesn't show up in my radial menu while in the zone.

**Comment by JonasDev99** [comment]
> working fine for me 🤔

Now that's weird 🤨

**Comment by DannysRP** [comment]
Yeah I don't know either. I have fresh installs of both but radial options on customs does not show up. No errors in F8 or console

**Comment by JonasDev99** [comment]
image

This fixes it but idk if this will break something else.

**Comment by ItsANoBrainer** [comment]
Thankyou for the more detailed information, currently finishing up a new implementation that should resolve this issue.

**Comment by MadManDanCat** [comment]
there is no code in the radial menu for qb-customs yet you are saying we need this version to use the customs with radial.... kinda miss information or maybe its just not actually done yet

**Comment by ItsANoBrainer** [comment]
> there is no code in the radial menu for qb-customs yet you are saying we need this version to use the customs with radial.... kinda miss information or maybe its just not actually done yet

Maybe you should do some research before insulting my work? This code has EXPORTS that allow OTHER RESOURCES to add and remove options dynamically to the radial menu. There is no code here for customs because it doesnt need it, the code for adding/removing is done with exports in qb-customs.

**Pull request merged**
