### PR TITLE
Fix for https://github.com/qbcore-framework/qb-radialmenu/issues/105

### PR DESCRIPTION
**Pull request by RestrictedNova**
**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Comment by Andyauk** [comment]
looking good. i have some that my own, where would i find them RadialMenu.js ?
like map-marker and cut, laptop-house

**Comment by RestrictedNova** [comment]
You are able to change them in the config.lua

**Comment by Andyauk** [comment]
> You are able to change them in the config.lua. You will most likely also need to go to the font awesome website and check the ones you want as I had to go through the ones that wasn't recognised and find the original names on the site. For instance laptop-house is gonna be house-laptop

thanks

**Review by IdrisDose — APPROVED** [review]

**Comment by itsjustyoan** [comment]
thanks for the bug update! i have a question. i have to hold F1 key in order for it to stay. is there a way to make it static?

**Pull request merged**
